# Config file for iProtector by LDX;

# Settings for default area messages
Text:

  # Display text messages on area enter / leave
  Textmsg: true

  # Enter area text prefix (followed by areaname)
  Enter: Enter area

  # Leave area text prefix (followed by areaname)
  Leave: Leaving area

# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?
  God: false

  # Keep players from editing the world?
  Edit: false

  # Keep players from touching blocks and activating things like chests?
  Touch: false

# Settings for unprotected areas in individual worlds:
Worlds:

  DEFAULT:

    # Keep players from getting hurt?
    God: false

    # Keep players from editing the world?
    Edit: false

    # Keep players from touching blocks and activating things like chests?
    Touch: false
